version: "3"
services:
  backend:
    container_name: backend
    build: ./backend
    # ports:
    #   - "5000:5000"
    restart: always
    env_file:
      - .env
    volumes:
      - ./backend:/myportfolio
    depends_on:
      - db
    networks:
      - nginx_backend_network
      - backend_network

  db:
    container_name: db
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/postgresql/data
    networks:
      - backend_network

  frontend:
    container_name: frontend
    build: ./frontend
    # ports:
    #   - "3000:3000"
    restart: always
    env_file:
      - .env
    volumes:
      - ./frontend/src:/app/src
    networks:
      - nginx_frontend_network

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - nginx_frontend_network
      - nginx_backend_network

volumes:
  mydatabase:

networks:
  nginx_frontend_network:
  nginx_backend_network:
  backend_network:
